

HOME_DIR="/cygdrive/c/users/neil"
SRC_DIR=f"{ HOME_DIR }/OneDrive/Documents/DR534-21-Files"

STAFF_ROSTER = f"{ SRC_DIR }/Staff Roster 9.4 4 PM.xlsx"
STAFF_ROSTER_SHEET_NAME = "Staff Roster"
STAFF_ROSTER_TITLE_ROW = 4

OUTPROCESSED_ROSTER = f"{ SRC_DIR }/Out Processed Staff Report 9.4 4 PM .xlsx"
#OUTPROCESSED_ROSTER_SHEET_NAME = "Staff Roster"
OUTPROCESSED_ROSTER_SHEET_NAME = "Sheet1"
OUTPROCESSED_ROSTER_TITLE_ROW = 6

VEHICLES = f"{ SRC_DIR }/Vehicles.xlsx"
VEHICLES_SHEET_NAME = "Sheet1"

#OPEN_RENTALS_DIR = f"{ HOME_DIR }/American Red Cross/NHQDCSDLC - FY21 Avis Report"
OPEN_RENTALS_DIR = SRC_DIR
OPEN_RENTALS = f"{ OPEN_RENTALS_DIR }/ARC Open Rentals - 08-31-2020.xlsx"
OPEN_RENTALS_SHEET_NAME = "Open RA"
OPEN_RENTALS_DRS = [ "534", "534-2021", 'DR534', 'DR534-21', '534-', 'DR 534', 'DR#: 534' ]
OPEN_RENTALS_TITLE_ROW = 3

#CLOSED_RENTALS = OPEN_RENTALS
CLOSED_RENTALS = f"{ OPEN_RENTALS_DIR }/Open_and_Closed_Rental_Report 9-2 2020.xlsx"
CLOSED_RENTALS_SHEET_NAME = "Closed RA"
CLOSED_RENTALS_TITLE_ROW = 4

#DST_DIR = SRC_DIR
DST_DIR = "."
OUTPUT_WB = f"{ DST_DIR }/merged.xlsx"
MERGED_SHEET_NAME = "No Veh Entry"
RECONCILED_SHEET_NAME = "Reconciled"
CURRENT_SHEET_NAME = "Current"
OUTPROCESSED_SHEET_NAME = "Outprocessed"
MISSING_SHEET_NAME = "Not on Staff Roster"


